# --- Identificación del Proyecto ---
sonar.projectKey=calculator-angular
sonar.projectName=Calculator Angular Frontend
sonar.projectVersion=1.0.0

# --- Configuración de Rutas de Código ---
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts

# --- Configuración de Tests ---
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
# Si ejecutas pruebas de cobertura, se guardarán aquí:
sonar.javascript.lcov.reportPaths=coverage/angularCalc/lcov.info

# --- Conexión al Servidor ---
# IMPORTANTE: En Jenkins usa el nombre del contenedor o la IP de red
sonar.host.url=http://sonarqube:9000
